version: '2'
services:
  #
  # NodeJs
  gcloud:
    image: google/cloud-sdk
    # name the created container..
    container_name: ${APP_NAME}
    # from that build image..
    # exposing..
    ports:
      - "49161:8080"
    # and loading env into the created container..
    env_file: .env
    volumes_from:
      - persistent-data
    working_dir: /root
    stdin_open: true
    tty: true

  #
  # Persistence
  persistent-data:
    image: busybox
    container_name: ${APP_NAME}-volume
    command: "true"
    volumes:
      - ${APP_PERSISTENT}:/root

